### PR TITLE
remove z-shell/zsh-fancy-completions

### PR DESCRIPTION
**Pull request by Lunarequest**
z-shell/zsh-fancy-completions has either been deleted or privated, it is no longer on github and this breaks the @z-shell meta annex. There should be some guidelines on this added from maintainers. just deleting the repo with cleaning up elsewhere is bound to cause a lot of problems.

### CODE REVIEW

**Review by ss-o — COMMENTED** [review]
Help with the maintenance of plugins would help more than deleting them. :rocket: (wooden joke :upside_down_face:).

Due to unforeseen circumstances, I wasn't able to complete the sketch.
It's useable but requires additional testing/adjusting to being done. :chart_with_upwards_trend: 

Just confirm I should approve this PR, apologies for the inconvenience, and thank you for informing me of the issue. :red_circle: 

> **Note**
>- The issue can be solved by skipping the broken plugin name to the `skip` ice modifier.

https://github.com/z-shell/zsh-fancy-completions/

**Comment by Lunarequest** [comment]
no worries, any plugins in particular that need attention asap?

**Comment by ss-o** [comment]
I am unaware of your skill sets (seen you have a nice blog, and also read a few posts and found them interesting). Z-Shell is a community project driven by a passion for tech, so everyone is welcome to participate in any topic from technical writing to project management, contributions are what make the open-source community such an amazing place to learn, inspire, and create. Any participation is welcome and can be discussed on how we can materialize it. :tada: :handshake:

**Comment by ss-o** [comment]
Also, I forgot to mention that zsh-fancy-completions are not fully compatible with the current Zi version, as soon it will have better performance and approx. 30% faster (currently has on [next2](https://github.com/z-shell/zi/tree/next2) branch), because of completion management, so when merged, I'll be able to finish the zsh-fancy-completions and improve other plugins. :rocket:

**Review by ss-o — APPROVED** [review]

**Comment by ss-o** [comment]
The changed meta-plugins group is because of better compatibility.

**Pull request merged**
